### ISSUE TITLE
Lambda bundled with webpack can't import sharp module

### ISSUE THREAD

**Issue by brandonregard** [pH200/sharp-layer#3]
Using webpack (5.88.2) with your 0.32.6 release (https://github.com/pH200/sharp-layer/releases/download/0.32.6/release-x64.zip). I have the same `sharp` package installed locally (linux/x86).

I have created the layer using the zip referenced above (nodejs 18, same as local) and added to the Lambda that needs it. Source has been bundled with webpack.

Receiving the following: `Runtime.ImportModuleError: Error: Cannot find module 'sharp'`.

 I think it may have to do with the `externals` property used by webpack. I have followed the instructions from the sharp documentation: https://sharp.pixelplumbing.com/install#aws-lambda. Any experience here?

Here is the full CloudWatch log error:
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'sharp'\nRequire stack:\n- /var/task/EventIotTriggerPreTraffic.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'sharp'",
        "Require stack:",
        "- /var/task/EventIotTriggerPreTraffic.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```
Webpack `externals` config:
```
externals: {
    'sharp': 'commonjs sharp'
}
```
Also tried (path from exec  `ls -FlaR /opt` on ephemeral storage):
```
externals: {
    'sharp': '/opt/nodejs/node18/node_modules/sharp'
}
```

**Comment by pH200** [comment]
Did you add the layer to your function?

I just tested 0.32.6 on my aws console, it worked just fine.

```js
const sharp = require('sharp');
exports.handler = async (event) => {
  console.log(require.resolve('sharp'));
  return {
    statusCode: 200,
    body: sharp.versions.sharp
  };
}
```

![image](https://github.com/pH200/sharp-layer/assets/1430310/c7c01b9c-a20f-4b6e-b839-93ea3d42b7e4)

And it seems like you're running esm modules instead of commonjs. Maybe you can try the followings:
```
externals: {
  sharp: 'sharp'
}
```

**Comment by brandonregard** [comment]
Thanks for you reply @pH200.

It gave me a good way to validate that the layer is working as expected. It is. I swapped out my Lambda code with vanilla JavaScript based on your example to validate the layer. I then converted that Lambda to Typescript and ran through webpack. I was able to diagnose the issue with `tsconfig.json`. I was missing a `path` entry to the `sharp` module.
